version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://root:pass@mongodb:27017/admin?authSource=admin
      - JWT_SECRET=3a7f5d9c1b6e8f2a4d9c7b5e8f3a6d2c1b9e7f5a8d3c6b9e2f5a7d1c8b6e9f4a3d7
      - PORT=5000
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5173
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data: